Reference section for large screens
josueahadi/baumeister pull request #10
Opened 2024-05-29 10:43 UTC by Chartine02

Implemented the reference section for large screens

2024-05-29 12:32 UTC, beylar commented
please correct the padding and alignment of the text

2024-05-29 14:10 UTC, gloriaumutoni approved these changes
looks good

2024-05-30 09:09 UTC, josueahadi requested changes
@aimee-annabelle @Chartine02 The reference section looks superb on large screens. You can carry on and work on responsiveness for tablet and mobile screens.

2024-05-31 13:01 UTC, beylar approved these changes

2024-05-31 14:31 UTC, Ntwalii approved these changes
Well implemented.

2024-06-03 09:08 UTC, josueahadi approved these changes
It works as expected...kudos! :)

2024-06-03 09:26 UTC, Kingcedru commented on src/sections/reference.html
> +    alt=""
Add image description

2024-06-03 09:33 UTC, Kingcedru requested changes
Changes needed

2024-06-03 09:33 UTC, Kingcedru commented on src/sections/reference.html
> +    <a href="https://designpreis-brandenburg.de/    " target="_blank"
Remove space at the end of the href link.

2024-06-03 09:47 UTC, Kingcedru approved these changes
Done

2024-06-03 09:48 UTC, merged