Ft/data privacy
josueahadi/baumeister pull request #17
Opened 2024-06-03 09:56 UTC by beylar

Data privacy information

2024-06-03 15:56 UTC, josueahadi approved these changes
The data privacy page looks perfect

2024-06-04 08:52 UTC, Ntwalii approved these changes

2024-06-04 12:56 UTC, Kingcedru commented on src/sections/greenheader.html
> +
Remove these spaces

2024-06-04 12:59 UTC, Kingcedru requested changes
Changes needed.

2024-06-04 12:59 UTC, Kingcedru commented on src/sections/greenheader.html
> +       <img class="md:hidden" src="./src/images/white.svg">
You missed the alt attribute on this image tag

2024-06-04 12:59 UTC, Kingcedru commented on src/sections/header.html
> +
Remove spaces

2024-06-04 12:59 UTC, Kingcedru commented on src/sections/header.html
> +     <img class="md:hidden" src="./src/images/white.svg">
Also add the image description.

2024-06-05 13:08 UTC, josueahadi approved these changes

2024-06-05 13:12 UTC, josueahadi requested changes

2024-06-05 13:12 UTC, josueahadi commented on privacy.html
Excellent! All that is left is adding the recent changes from the footer hotfix branch to this page's footer, and this page will be complete.

2024-06-05 15:05 UTC, josueahadi approved these changes

2024-06-06 09:59 UTC, NoellaPromise approved these changes

2024-06-06 10:42 UTC, Kingcedru approved these changes

2024-06-06 10:43 UTC, merged