fix: services section break points text breaking
josueahadi/baumeister pull request #19
Opened 2024-06-05 10:14 UTC by aimee-annabelle

The responsiveness of the services section was broken for some screens. This PR is for the fix on those breaks; all mobile, tablet, and big screens have been fixed.

2024-06-05 13:49 UTC, josueahadi approved these changes

2024-06-05 14:01 UTC, gloriaumutoni approved these changes
nice job

2024-06-05 14:13 UTC, beylar approved these changes

2024-06-05 16:45 UTC, Kingcedru requested changes
Some changes needed

2024-06-05 16:45 UTC, Kingcedru commented on src/sections/services.html
> +      class="h-full xl:h-auto z-0 flex self-end"
Add image description

2024-06-05 17:53 UTC, aimee-annabelle commented on src/sections/services.html
> +      class="h-full xl:h-auto z-0 flex self-end"
resolved

2024-06-06 05:21 UTC, Kingcedru approved these changes

2024-06-06 05:21 UTC, merged