Adjust the z-index of the sticky shape
josueahadi/baumeister pull request #20
Opened 2024-06-05 10:23 UTC by Chartine02

Adjusted the z-index of the sticky shape to go behind the red shape in the footer

2024-06-05 12:21 UTC, josueahadi requested changes
Implement the suggested changes. Otherwise everything looks good!

2024-06-05 12:21 UTC, josueahadi commented on .vscode/settings.json
> +{
This file is not necessary. Add the `.vscode` to .gitignore so files like this will be ignored.

2024-06-05 12:35 UTC, josueahadi commented on .gitignore
> +.vscode
Well done!

2024-06-05 12:37 UTC, josueahadi approved these changes

2024-06-05 13:37 UTC, Ntwalii approved these changes

2024-06-05 15:20 UTC, josueahadi approved these changes

2024-06-06 11:17 UTC, NoellaPromise approved these changes

2024-06-06 11:17 UTC, merged