Line spacing in the contact
josueahadi/baumeister pull request #29
Opened 2024-06-07 14:17 UTC by Chartine02

Line spacing in the contact

2024-06-07 14:30 UTC, josueahadi approved these changes

2024-06-10 06:35 UTC, gloriaumutoni approved these changes

2024-06-10 07:42 UTC, Kingcedru requested changes
Remove the conflict indication symbols like >>>> and <<<

2024-06-10 07:49 UTC, Kingcedru approved these changes
Done

2024-06-10 07:49 UTC, merged