ft: yellow sticky shape
josueahadi/baumeister pull request #3
Opened 2024-05-28 09:22 UTC by aimee-annabelle

Added a yellow sticky shape centered on the page, which will stay on top when scrolled

2024-05-28 10:13 UTC, Ntwalii commented
Please pull dev to get the recent changes

2024-05-28 12:40 UTC, josueahadi commented
@aimee-annabelle, there's a conflict in your index.html document that needs to be addressed.

2024-05-28 15:20 UTC, Ntwalii approved these changes
The shape has been implemented successfully.

2024-05-28 15:25 UTC, gloriaumutoni approved these changes

2024-05-30 08:22 UTC, Kingcedru commented on src/sections/sticky.html
> +  <img src="../src/images/sticky-shape.svg" alt="" />
Try to fill the alt attribute with the image description.
example:
`<img src="../src/images/sticky-shape.svg" alt="Yellow shape" />`

2024-05-30 08:25 UTC, Kingcedru approved these changes

2024-05-30 08:27 UTC, Kingcedru requested changes
You can check the review I provided.

2024-05-30 08:33 UTC, Kingcedru approved these changes

2024-05-30 08:33 UTC, merged